### ISSUE TITLE
Error message could hide nonpython info

### ISSUE THREAD

**Issue by dz0** [aroberge/reeborg#116] opened 2015-05-18 02:46 UTC
```py
if front_is_clear()   # :
        move()          
```
shows
```
SyntaxError

invalid syntax
→ common_def.generic_translate_python(src, my_lib, "from reeborg_en import *", highlight) module exec-tfsxmftj line 1 if front_is_clear() # :
```
Though for student would be better 
```
SyntaxError

invalid syntax
line 1 if front_is_clear() # :
```
maybe Reeborg could hide/collapse the extra info?

**Comment by aroberge** [comment] 2015-05-18 11:44
This bug was caused by the fix for #114.  The change has been reverted for the "old" code, and the "new" code (world_dev.html) has both the fix for #114 and a fix for this bug.

**Closed** 2015-05-18 13:05 UTC
Labels: bug
