### ISSUE TITLE
import to library vs import program

### ISSUE THREAD

**Issue by mikeygoldweber** [aroberge/reeborg#302] opened 2016-09-04 14:51 UTC
When I import a file to the library it also populates the program code window with the same file. The import function, instead of working independently between the code window and the library seems connected.

**Comment by aroberge** [comment] 2016-09-04 15:12
I cannot reproduce the issue; I suspect I am misunderstanding.

What I did: 
1. I clicked on "Additional options"
2. I clicked on "import library from a file" at the bottom of the window that opened.
3. I selected a python file from my computer

The library editor content was replaced by the content of the python file, and the content of the editor was not replaced. This test was done using Chrome.

**Comment by mikeygoldweber** [comment] 2016-09-04 15:21
Here is what I did:

1. selected Additional Operations
2. selected "import library from a file" at the bottom of the window that opened.
3. selected a python file from my computer

The library editor was replaced by the specified file.

I then
4. selected “import program from file”
5. selected a python file from my computer

At this point both the library editor and the code editor had the same file: the most recently selected python file.

mike


>

**Comment by aroberge** [comment] 2016-09-04 15:24
Ok, I can definitely reproduce this ... and cannot immediately see how this could happen when looking at the code.  I will try to solve this as a priority item.

**Comment by mikeygoldweber** [comment] 2016-09-04 15:25
I always feel bad when I uncover a bug…. sorry

mike

**Comment by aroberge** [comment] 2016-09-04 15:27
No need to apologize ... I don't mind fixing bugs (I find it to be a welcome distraction).

**Comment by aroberge** [comment] 2016-09-04 15:39
It should be fixed now.

The bug could also have messed up loading worlds.  I will close this bug when I obtain independent confirmation that it is fixed.

**Comment by mikeygoldweber** [comment] 2016-09-04 15:42
It is not working for me…

Do I need to clear cookies or restart my browser?

mike

**Comment by aroberge** [comment] 2016-09-04 15:45
It may be a problem with reeborg.js being cached; forcing reload usually is all that is required.  Restarting the browser (or opening a private window) might be a better solution for a thorough test.

**Comment by mikeygoldweber** [comment] 2016-09-04 15:48
things worked corrected with a new private window in chrome.  I agree… pushing the fix through required getting rid of/around the cached code.

mike

**Comment by aroberge** [comment] 2016-09-04 15:53
Previously, I have set up .htaccess to instruct browsers to cache js files for 6 hours; this should be sufficient for most users to ensure that they have the latest version when they load the site on a given day, while reducing the number of files fetched each time the site is reloaded.  For many browsers, ctrl-F5 is sufficient to ensure that the cached instructions are bypassed and that all files are reloaded.

**Closed by aroberge** 2016-09-04 15:53 UTC
Labels: bug

**Comment by mikeygoldweber** [comment] 2016-09-08 18:21
Andre,
	I am having an issue with the builtin predicates (e.g. right_is_clear())


Consider the code snippet:

foo = UsedRobot(1, 1,’e’, 10)

if (foo.front_is_clear()):
	foo.move()
		seemingly always evaluates to true regardless of the presence of a wall…eventually hits a wall and produces an error

while

if (front_is_clear()):
	foo.move()
		works fine - as long as there is only one robot in the program


This behavior seems incorrect to me.

mike goldweber

**Comment by aroberge** [comment] 2016-09-09 02:11
This is/was a most embarassing error, introduced during the last major refactoring.  In the Javascript code (called by the Python code), when dealing with non-default robot, I had a line of code like

    front_is_clear(foo)

instead of

    return front_is_clear(foo)

(And, to my shame, I forgot to include the `return` keyword on many similar other tests dealing with non-default object.   Obviously, my existing unit tests (focuses on a single robot) are clearly lacking...
